//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/artyomfadeyev/GitHub/ITMO-PROBLEMS/Programming-Technologies/IV semester/Solutions/_2CodeGen/JavaServerParser/AntlrCSharp/Server.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IServerListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ServerBaseListener : IServerListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.package_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackage_name([NotNull] ServerParser.Package_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.package_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackage_name([NotNull] ServerParser.Package_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.import_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_name([NotNull] ServerParser.Import_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.import_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_name([NotNull] ServerParser.Import_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] ServerParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] ServerParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.package"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackage([NotNull] ServerParser.PackageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.package"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackage([NotNull] ServerParser.PackageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.import_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_([NotNull] ServerParser.Import_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.import_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_([NotNull] ServerParser.Import_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.annotation_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation_header([NotNull] ServerParser.Annotation_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.annotation_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation_header([NotNull] ServerParser.Annotation_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.annotation_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation_arguments([NotNull] ServerParser.Annotation_argumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.annotation_arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation_arguments([NotNull] ServerParser.Annotation_argumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] ServerParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] ServerParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModifier([NotNull] ServerParser.ModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.modifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModifier([NotNull] ServerParser.ModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_type([NotNull] ServerParser.Var_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.var_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_type([NotNull] ServerParser.Var_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] ServerParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] ServerParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.return_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_type([NotNull] ServerParser.Return_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.return_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_type([NotNull] ServerParser.Return_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_type([NotNull] ServerParser.Model_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_type([NotNull] ServerParser.Model_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_name([NotNull] ServerParser.Model_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_name([NotNull] ServerParser.Model_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.parents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParents([NotNull] ServerParser.ParentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.parents"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParents([NotNull] ServerParser.ParentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_header([NotNull] ServerParser.Model_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_header([NotNull] ServerParser.Model_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_attribute([NotNull] ServerParser.Model_attributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model_attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_attribute([NotNull] ServerParser.Model_attributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel_annotation([NotNull] ServerParser.Model_annotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel_annotation([NotNull] ServerParser.Model_annotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModel([NotNull] ServerParser.ModelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.model"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModel([NotNull] ServerParser.ModelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_name([NotNull] ServerParser.Function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_name([NotNull] ServerParser.Function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_arg([NotNull] ServerParser.Function_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_arg([NotNull] ServerParser.Function_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_args([NotNull] ServerParser.Function_argsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_args([NotNull] ServerParser.Function_argsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_header([NotNull] ServerParser.Function_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_header([NotNull] ServerParser.Function_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_annotation([NotNull] ServerParser.Function_annotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_annotation([NotNull] ServerParser.Function_annotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] ServerParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] ServerParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_body([NotNull] ServerParser.Function_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.function_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_body([NotNull] ServerParser.Function_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ServerParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] ServerParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ServerParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] ServerParser.RootContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
