//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Github/ITMO-PROBLEMS/Programming-Technologies/IV semester/Solutions/_2CodeGen/Parser/AntlrParser\Server.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ServerParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IServerVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.package_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_name([NotNull] ServerParser.Package_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.import_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_name([NotNull] ServerParser.Import_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] ServerParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.package"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage([NotNull] ServerParser.PackageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.import_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImport_([NotNull] ServerParser.Import_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.annotation_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation_header([NotNull] ServerParser.Annotation_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.annotation_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation_arguments([NotNull] ServerParser.Annotation_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] ServerParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] ServerParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.var_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_type([NotNull] ServerParser.Var_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] ServerParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_type([NotNull] ServerParser.Return_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel_type([NotNull] ServerParser.Model_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel_name([NotNull] ServerParser.Model_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.parents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParents([NotNull] ServerParser.ParentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel_header([NotNull] ServerParser.Model_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model_attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel_attribute([NotNull] ServerParser.Model_attributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel_annotation([NotNull] ServerParser.Model_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.model"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModel([NotNull] ServerParser.ModelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] ServerParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_arg([NotNull] ServerParser.Function_argContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_args([NotNull] ServerParser.Function_argsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_header([NotNull] ServerParser.Function_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_annotation([NotNull] ServerParser.Function_annotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] ServerParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.function_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_body([NotNull] ServerParser.Function_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ServerParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] ServerParser.RootContext context);
}
